[providers]
node = "18.x"

[phases.setup]
nixPkgs = ["nodejs_18", "python3", "python3Packages.pip", "ffmpeg", "python3Packages.setuptools", "curl", "ca-certificates"]

[phases.install]
dependsOn = ["setup"]
cmds = [
  "npm cache clean --force || true",
  "rm -rf node_modules || true",
  "rm -rf package-lock.json || true",
  "npm install --legacy-peer-deps --no-audit --no-fund",
  "pip3 install --break-system-packages --upgrade yt-dlp",
  "which yt-dlp || echo 'yt-dlp not found in PATH'",
  "yt-dlp --version || echo 'yt-dlp version check failed'"
]

[phases.build]
dependsOn = ["install"]
cmds = ["npm run build"]

[start]
cmd = "npm start"

[variables]
NODE_ENV = "production"
PATH = "/root/.local/bin:/usr/local/bin:$PATH"
NPM_CONFIG_CACHE = "/tmp/.npm"
TEMP_DIR = "/tmp/temp-downloads"
