[providers]
node = "18.x"

[phases.setup]
nixPkgs = ["nodejs_18", "ffmpeg"]

[phases.install]
dependsOn = ["setup"]
cmds = [
  "npm cache clean --force || true",
  "rm -rf node_modules || true",
  "rm -rf package-lock.json || true",
  "npm install --legacy-peer-deps --no-audit --no-fund"
]

[phases.build]
dependsOn = ["install"]
cmds = ["npm run build"]

[start]
cmd = "npm start"

[variables]
NODE_ENV = "production"
NPM_CONFIG_CACHE = "/tmp/.npm"
