[phases.setup]
nixPkgs = ["nodejs_18", "python3", "python3Packages.pip", "ffmpeg"]

[phases.install]
cmds = [
  "npm ci",
  "pip3 install --user yt-dlp"
]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "npm start"

[variables]
NODE_ENV = "production"
PATH = "/root/.local/bin:$PATH"
