[phases.setup]
nixPkgs = ["nodejs_18", "python3", "python3Packages.pip", "ffmpeg"]

[phases.install]
cmds = [
  "npm cache clean --force || true",
  "rm -rf node_modules || true",
  "npm install --no-package-lock --legacy-peer-deps",
  "pip3 install --user yt-dlp"
]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "npm start"

[variables]
NODE_ENV = "production"
PATH = "/root/.local/bin:$PATH"
